name: doc
on:
  push:
    branches:
      - main

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry install

    - name: Build documentation
      run: |
         poetry run mkdocs build

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.GH_PAT }}
        branch: gh-pages
        folder: site
